### PR TITLE
reimplements multi-highlight

### LINKED ISSUE #122: Cannot make more than one highlighted words section
## Description

Goon chat's word highlighter is currently broken as it only allows one highlighted colour type to be shown.

## Difference between expected and actual behavior

It should allow for multiple words to be highlighted with a multitude of different colours.
Currently it only allows one.

## Steps to reproduce

Open up Goon chat's settings in game and see that only one text box is allowed to be used rather than multiple.
image

There should be an option to add more than one text box but currently as shown above, there is no option.
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by stanalbatross**
# About the pull request

reimplements old chat multi-highlight

fixes #122

image

# Explain why it's good for the game

easier highlighting and more customisable

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Stanalbatross, TheDonkified
ui: re-added the old multiple highlight system, originally made by thedonkified. You can add up to 10 individual highlights, customise their colours, and toggle if they highlight the whole message or not.
ui: you can now use regex for text highlighting. The syntax is /[regex expression]/, eg /dog[0-9]/. There are no quantifiers, but you can use capture groups. The regex must read a minimum of two characters.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
we really should try to get this upstream because it’ll be overwritten next time we update tgui

File: tgui/packages/tgui-panel/settings/SettingsPanel.js [hunk 1]
```diff
@@ -157,62 +152,41 @@ export const SettingsGeneral = (props, context) => {
...
+      </Button>
+    </Section>
+  );
+};
+
+const TextHighlightSettings = (props, context) => {
+  const highlightSettings = useSelector(context, selectHighlightSettings);
+  const dispatch = useDispatch(context);
+  return (
+    <Section fill>
```
Comment (harryob) [inline tgui/packages/tgui-panel/settings/SettingsPanel.js:166]:
```suggestion
    <Section fill scrollable>
```
otherwise you can add too many sections and it goes off the bottom of the window

**Review by harryob — CHANGES_REQUESTED** [review]
