### PR TITLE
Fixes Nuke being able to nuke before decryption mentioned in #8769 

### LINKED ISSUE #8769: Nuclear Fission Explosive can be activated even though decryption hasn't finished.
## Testmerges
<a href="https://github.com/cmss13-devs/cmss13/pull/8378">#8378: 'Yautja Ship - Complete Remake &amp; more...' by Zenith00000 at commit 0cdba4c8ed</a><br><a href="https://github.com/cmss13-devs/cmss13/pull/8628">#8628: 'Adds Fan The Hammer to the M44 revolver' by Red-byte3D at commit f924b770f6</a><br><a href="https://github.com/cmss13-devs/cmss13/pull/7703">#7703: 'Hivelord Strain: Designer [TM]' by Venuska1117 at commit ffd31cfeca</a><br><a href="https://github.com/cmss13-devs/cmss13/pull/8764">#8764: 'Cleanup browser.dm' by Drulikar at commit 80c1c4f577</a><br>

## Round ID
26867

## Description of the bug
On round 26867 A Pilot simply activated the nuke because the "decryption halted" message played. There was ~230 seconds left on decryption, but somehow they were able to just "activate" the nuke

## What's the difference with what should have happened?
Nuke shouldn't activate until decryption has finished.

## How do we reproduce this bug?
I was not there but:
1. Halt decryption
2. Activate the Nuke
3. Maybe start decryption again at some point between the two above steps.
4. Nuke goes off with time left on decryption.

## Attached logs
```
N/A
```

## Additional details
- Author: SmellyHippie
- Admin: SmellyHippie
- Note: None

### PR DESCRIPTION
**Pull request by Aurallianz**
# About the pull request
Fixes #8769 

# Explain why it's good for the game
Nuking before decryption is BS

# Testing Photographs and Procedure
changing an && to an ||, because you want all of those cases to be true not just one.
[video in devchat of the fix working](https://cdn.discordapp.com/attachments/745447048261795890/1350723634221551671/nukefix.mp4?ex=67d7c6e9&is=67d67569&hm=eb5adf0e69b3baf166af9c0e6fb5528e4538075ca80c75ae2802c377f4fafd36&
)
admins are notified if users bypass the TGUI check.
image

# Changelog
:cl:
fix: fixes nuke Before Decryption
/:cl:

### CODE REVIEW

**Comment by TheGamerdk** [comment]
This sounds like missing input checking in the actual .dm file, should probably fix that too

**Comment by Aurallianz** [comment]
I don't entirely think that anything else is an issue, it's now operating as intended & how it previously was. I wanted to avoid breaking anything else tbh. Plus there was no checks previously in the dm files.

**Comment by TheGamerdk** [comment]
> I don't entirely think that anything else is an issue, it's now operating as intended & how it previously was. I wanted to avoid breaking anything else tbh. Plus there was no checks previously in the dm files.
> 
> Basically the system was just taking if any of those were false and allowing you to nuke. Instead of checking if all of them were false. Pretty simple, there is simply no way to break it now.

The wording of the bug report makes it sound like the UI allowed the nuke to go off without being decrypted.

This needs to be fixed in the .dm code, as a malicious user can send whatever requests they want, bypassing whatever checks added in the UI/.tsx

**Comment by Aurallianz** [comment]
oookay well, in theory this is the last thing that needed to be changed, again, in theory you should not be able to do that, and if it gets called magically, that person is probably cheating... SOOO

File: tgui/packages/tgui/interfaces/NuclearBomb.tsx [hunk 1]
```diff
@@ -26,8 +26,8 @@ type Data = {
 export const NuclearBomb = () => {
   const { act, data } = useBackend<Data>();
 
-  const cantNuke = !data.anchor && !!data.safety && !data.decryption_complete;
-  const cantDecrypt = !data.anchor && data.decryption_complete;
+  const cantNuke = !data.anchor || data.safety || !data.decryption_complete;
```
Comment (kiVts) [inline tgui/packages/tgui/interfaces/NuclearBomb.tsx:29]: the double !! is a "double negation". read about it here: https://stackoverflow.com/questions/10467475/double-negation-in-javascript-what-is-the-purpose

After reading, return it.

File: code/game/machinery/nuclearbomb.dm [hunk 2]
```diff
@@ -169,6 +172,11 @@ GLOBAL_VAR_INIT(bomb_set, FALSE)
 			if(!ishuman(ui.user))
 				return
 
+			if(decryption_time != 0) //This should never get called unless the decryption process is still ongoing, in which case a user has modified their client.
+				to_chat(ui.user, SPAN_INFO("The encryption process must be completed first!"))
+				message_admins("\The [src] has been attempted to be activated by [key_name(ui.user, 1)], this should not be possible [ADMIN_JMP_USER(ui.user)]")
```
Comment (kiVts) [inline code/game/machinery/nuclearbomb.dm:177]:
```suggestion
				message_admins("[key_name(ui.user, 1)] [ADMIN_JMP_USER(ui.user)] attempted to activate [src] before its ready, this shouldn't be possible.")
```

File: tgui/packages/tgui/interfaces/NuclearBomb.tsx (hunk 1 above)
Comment (kiVts) [reply tgui/packages/tgui/interfaces/NuclearBomb.tsx:29]: also, fyi but this is bit shitcode as for var names, Im not telling you to change anything since you didnt add it, but *never* name vars like that.

File: code/game/machinery/nuclearbomb.dm [hunk 3]
```diff
@@ -16,6 +16,9 @@ GLOBAL_VAR_INIT(bomb_set, FALSE)
 	var/being_used = FALSE
 	var/end_round = TRUE
 	var/timer_announcements_flags = NUKE_SHOW_TIMER_ALL
+	var/decryption_time = 10 MINUTES
```
Comment (kiVts) [inline code/game/machinery/nuclearbomb.dm:19]: change this to zero and override it on the tech nuke to 10.

**Review by kiVts — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/interfaces/NuclearBomb.tsx (hunk 1 above)
Comment (Aurallianz) [reply tgui/packages/tgui/interfaces/NuclearBomb.tsx:29]: I agree with you; you don't understand how long it took me to find that fucking line of code and understand what it meant.
I can re-add the double negation (normal people would just use tobool 💀

File: code/game/machinery/nuclearbomb.dm [hunk 4]
```diff
@@ -169,6 +172,11 @@ GLOBAL_VAR_INIT(bomb_set, FALSE)
 			if(!ishuman(ui.user))
 				return
 
+			if(decryption_time != 0) //This should never get called unless the decryption process is still ongoing, in which case a user has modified their client.
+				to_chat(ui.user, SPAN_INFO("The encryption process must be completed first!"))
+				message_admins("[key_name(ui.user, 1)] [ADMIN_JMP_USER(ui.user)] attempted to activate [src] before its ready, this shouldn't be possible.")
```
Comment (realforest2001) [inline code/game/machinery/nuclearbomb.dm:177]:
```suggestion
				message_admins("[key_name(ui.user, 1)] [ADMIN_JMP_USER(ui.user)] attempted to activate [src] before it is ready, this shouldn't be possible.")
```

**Review by realforest2001 — APPROVED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Aurallianz** [comment]
This is slightly stale but the new one still lacks a server-side check for nuke operation so ill deal with this shortly

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Aurallianz** [comment]
Dont merge this for now Im gonna go test it and whatnot again make sure with the new changes it hasn't broken anything

**Comment by Aurallianz** [comment]
This seems to be fine, it is not causing issues

**Review by Git-Nivrak — APPROVED** [review]
